name: PR Pre Merge

on:
  pull_request:
    branches: [ $default-branch ]

env:
  OS_VERSIONS: [ubuntu-16.04]
  NODE_VERSIONS: [12.x]

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ${{ OS_VERSIONS }}
        node: ${{ NODE_VERSIONS }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm run setup
      - run: npm run lint
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ${{ OS_VERSIONS }}
        node: ${{ NODE_VERSIONS }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm run setup
      - run: npm run test
